# production.yml

version: '3.7'

services:
  client:
    container_name: client_production
    build:
      context: .
      dockerfile: Dockerfile-production
    environment:
      - NODE_ENV=production
